# Welcome to Jekyll!
#

# Site settings
title: Open Cities Africa
description: |
  Open data today to build resilient and sustainable societies tomorrow
owner: GFDRR # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opencitiesproject.org" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>

# Build settings
markdown: kramdown
permalink: pretty
#sass:
#  style: compressed

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "#footer", text: "Partners"}
 - {permalink: "/resources/", text: "Resources"}

cityLinks:
  - {permalink: "/accra/", text: "Accra"}
  - {permalink: "/antananarivo/", text: "Antananarivo"}
  - {permalink: "/brazzaville/", text: "Brazzaville"}
  - {permalink: "/uganda/kampala/", text: "Kampala"}
  - {permalink: "/kinshasa/", text: "Kinshasa"}
  - {permalink: "/monrovia/", text: "Monrovia"}
  - {permalink: "/ngaoundere/", text: "Ngaoundéré"}
  - {permalink: "/pointe-noire/", text: "Pointe-Noire"}
  - {permalink: "/saint-louis/", text: "Saint-Louis"}
  - {permalink: "/seychelles/", text: "Seychelles"}
  - {permalink: "/zanzibar-city/", text: "Zanzibar City"}

collections:
  - external_feed
